# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Burning Man
avatar: "/css/avatar-icon.png"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
  
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/css/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: "/css/avatar-icon.png"

baseurl: "/learn-jekyll" # the subpath of your site, e.g. /blog
url: "https://jan-martinek.github.io/learn-jekyll" # the base hostname & protocol for your site, e.g. http://example.com
background-image: "http://yacchan.link/wp-content/uploads/2015/07/believe.jpg"

# Build settings
markdown: kramdown
gems:
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - mock/*
background-image: url('http://yacchan.link/wp-content/uploads/2015/07/believe.jpg')
